### PR TITLE
Allow to configure network interface

### PR DESCRIPTION
**Pull request by ernestas-poskus**
@bertvv 

Hi, this let's to configure IP protocol and interface to use.
Default output this is same as 'ansible_default_ipv4'.

P.S. how about introducing CI (travis-ci.org) for this repo ?

### CODE REVIEW

**Comment by ernestas-poskus** [comment]
@bertvv ping

**Comment by bertvv** [comment]
Sorry! Thanks for the PR, I'm going to merge it when I have some time...

**Comment by bertvv** [comment]
I merged your PR, but made some changes to follow coding conventions. Role variables should always start with the role name, here `hosts_`.

Thanks for this contribution, it's very useful to be able to set the network interface, and I think I can use this trick in other roles, too.

**Comment by ernestas-poskus** [comment]
> Role variables should always start with the role name, here hosts_.

you could have said that, then I would change it in this PR

> Thanks for this contribution, it's very useful to be able to set the network interface, and I think I can use this trick in other roles, too.

Pleasure is mine

**Pull request merged**
